<?php

/**
 * Implements hook_menu().
 *
 * @return array
 */
function devconnect_developer_apps_menu() {
  $items = array();
  $items['user/%user/apps'] = array(
    'title' => t('My Apps'),
    'page callback' => 'devconnect_developer_apps_getlist',
    'page arguments' => array(1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  $items['user/%user/app-detail/%'] = array(
    'title' => t('App Detail'),
    'page callback' => 'devconnect_developer_apps_detail',
    'page arguments' => array(1, 3),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'weight' => 0,
  );

  $items['user/%user/apps/add'] = array(
    'title' => t('Add New App'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devconnect_developer_apps_edit_form', 1),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
  );

  $items['user/%user/apps/%/edit-app'] = array(
    'title' => t('Edit App'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devconnect_developer_apps_edit_form', 1, 3),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'weight' => 0,
  );

  $items['user/%user/apps/%/delete'] = array(
    'title' => t('Delete App'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('devconnect_developer_app_delete_form'),
    'access callback' => 'user_edit_access',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
    'weight' => 0,
  );

  return $items;
}

/**
 * Implements hook_variable_info().
 *
 * @param array $options
 *
 * @return array
 */
function devconnect_developer_apps_variable_info($options) {
  $variables['devconnect_show_analytics'] = array(
    'type' => 'boolean',
    'title' => t('Show Developer App performance tab'),
    'default' => FALSE,
    'description' => t('When this value is enabled, the \'Performance\' tab will be displayed on the developer app detail page.'),
  );
  return $variables;
}


/**
 * Implements hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return array
 */
function devconnect_developer_apps_theme($existing, $type, $theme, $path) {
  $items = array();
  $template_path = drupal_get_path('module', 'devconnect_developer_apps') . '/templates';


  $items['devconnect_developer_apps_list'] = array(
    'template' => 'devconnect_developer_apps_list',
    'arguments' => array('application_count' => 0, 'applications' => '', 'user' => NULL),
    'path' => $template_path
  );

  $items['devconnect_developer_credentials_list'] = array(
    'template' => 'devconnect_developer_credentials_list',
    'arguments' => array('credentials' => NULL),
    'path' => $template_path
  );

  $items['devconnect_developer_app'] = array(
    'template' => 'devconnect_developer_app',
    'arguments' => array(
      'account' => NULL,
      'access_type' => NULL,
      'callback_url' => NULL,
      'name' => NULL,
      'status' => NULL,
      'app_attributes' => array(),
      'credentials' => array(),
      'analytics_chart' => NULL
    ),
    'path' => $template_path
  );

  $items['devconnect_developer_line_chart'] = array(
    'template' => 'devconnect_developer_line_chart',
    'arguments' => array(
      'x_translate' => 0,
      'vertical_lines' => array(),
      'horizontal_lines' => array(),
      'axis_overhang' => 5,
      'x_axis' => NULL,
      'y_axis' => NULL,
      'y_axis_title' => NULL,
      'data_lines' => array(),
      'actual_chart_width' => 0,
      'actual_chart_height' => 0,
    ),
    'path' => $template_path
  );

  return $items;
}

/**
 * Page callback for "My Apps"
 *
 * @param $user
 *
 * @return string
 * @throws Exception
 */
function devconnect_developer_apps_getlist($user) {
  $module_path = drupal_get_path('module', 'devconnect_developer_apps');
  $library_path = libraries_get_path('jquery.selectlist');
  drupal_add_js("$module_path/devconnect_developer_apps.js");
  drupal_add_js($library_path . '/scripts/jquery.selectlist.pack.js');
  drupal_add_css("$module_path/devconnect_developer_apps.css");
  drupal_add_css($library_path . '/css/selectlist.css');

  try {
    $dc = new DevConnectApigeeDeveloperApp($user);
    $results = $dc->GetList();
    if ($results['code'] == 200) {
      $appNames = $results['data'];
      if (empty($appNames)) {
        return theme('devconnect_developer_apps_list', array(
          'application_count' => 0,
          'applications' => array(),
          'user' => $user,
        ));
      }
      else {
        $rows = array();
        foreach ($appNames as $appName) {
          $results = $dc->GetInfo($appName);
          if ($results['code'] == 200) {
            if (isset($results['data']['credentials'])) {
              $credentials = _devconnect_developer_apps_parse_credential_list($results['data']['credentials']);
              $app_keys = theme('devconnect_developer_credentials_list', array('credentials' =>$credentials));
            }
            else {
              // Should never happen; indicates broken API!
              $app_keys = '<img src="data:image/gif;base64,R0lGODlhJgAmAPEAAP/dAAECAwAAAAAAACH+M3JlZHVjZWQgYnl0ZSBjb3VudCBieSBodHRwOi8vd3d3LmN5YmVyc3BhY2UuY29tL3R1cAAh/wtORVRTQ0FQRTIuMAMBAAAAIfkEBQgAAQAsAAAAACYAJgABArSMj2nCog/jaU1ayYAG7HqUbVr3XaE4OmV0oun6tO4LTwJK4SosU/3+kXF8LpJHOMwVgazbzOdcWkLQm3I2bG6iV6zICIqOkg2vNLzMic20AJLIYUvf8LWc/FTH799ymmon17VVx9fnZlc1Zmj0Y+UXmJfQAnkSeahgCSjmdxbjVMnZSTj1CCraBaa1mQLVZmLV2kqkCmuYVYMkWbNwScprY1bLqzsMLGQMjIipDAHVXJoMUQAAIfkEBQEAAQAsCAAMABIADgABAiKUb6HLAg+YlC7Oi7PeDAjeeR8IeWBQjlx6pofmvhyianQBACH5BAUBAAEALAgADgAYAAwAAQIpFB6pyywNYxK0PonVAdlZym0H1SnVZpXLV5UiwKrrp74j6Yqgjch2UAAAIfkEBQEAAQAsCAAKABsADgABAjGMj3ki6m8EYLDaCxu+Um8lAdMDkKLYZcz6gesLx5R1hvW7nXrZHvsPFF2CuwoRaCgAADs=" alt="Missing Info" >';
            }

            $row = array(
              'app_name' => $appName,
              'callback_url' => $results['data']['callbackUrl'],
              'attributes' => _devconnect_developer_apps_get_attributes($results['data']['attributes']),
              'app_keys' => $app_keys,
              'delete_url' => 'user/' . $user->uid . '/apps/' . $appName . '/delete'
            );

            $rows[] = $row;
          }
        }
        return theme('devconnect_developer_apps_list', array(
          'application_count' => count($rows),
          'applications' => $rows,
          'user' => $user,
        ));
      }
    }
    else {
      $error = "STATUS: {$results['code']}-{$results['code_status']}; ";
      $error .= "Communication with the Apigee endpoint is compromised. Cannot get API Products List.";
      //if (user_access("administer organization settings")) {
        $error .= "<pre>" . print_r($results, TRUE) . "</pre>";
      //}
      throw new Exception($error);
    }
  } catch (Exception $e) {
    watchdog('devconnect_developer_apps', $e->getMessage(), array(), WATCHDOG_ERROR);
    return "<h4>" . $e->getMessage() . "</h4>";
  }
}

/**
 * Form constructor for adding/editing apps. Built via a menu callback to drupal_get_form().
 *
 * Incoming URL: user/%user/apps/add
 *
 * @return array
 */
function devconnect_developer_apps_edit_form($form, &$form_state, $account, $app_name = NULL) {

  $dc = new DevConnectApigeeDeveloperApp($account);
  if (isset($app_name)) {
    try {
      $result = $dc->GetInfo($app_name);
    } catch (Exception $e) {
      watchdog('devconnect_developer_apps', $e->getMessage(), array(), WATCHDOG_WARNING);
      drupal_not_found();
      exit;
    }
    $app_details = $result['data'];
  }
  // Set Title
  if (isset($app_details)) {
    $header_caption = t('Editing App “@app”', array('@app' => $app_name));
    //drupal_set_title($header_caption);
    $button_caption = t('Save App');
  }
  else {
    drupal_set_title('Add App');
    $header_caption = 'App Add Form';
    $button_caption = t('Create App');
    $owner_name = ($account->uid == $GLOBALS['user']->uid ? 'My' : $account->name . "'s");

    // Build Breadcrumbs
    $breadcrumb = array();
    $breadcrumb[] = l('Home', '<front>');
    $breadcrumb[] = l("$owner_name Apps", 'user/' . $account->uid . '/apps');
  }


  // Set Breadcrumbs
  drupal_set_breadcrumb($breadcrumb);

  $form = array();

  $form['header'] = array(
    '#type' => 'legend',
    '#title' => $header_caption,
  );

  if (isset($app_details)) {
    $form['machine_name'] = array(
      '#type' => 'item',
      '#title' => t('App Name'),
      '#markup' => check_plain($app_name),
      '#id' => 'existing_machine_name'
    );
  }
  else {
    $form['machine_name'] = array(
      '#title' => t('App Name'),
      '#type' => 'textfield',
      '#id' => 'new_machine_name',
      '#default_value' => '',
      '#required' => TRUE,
      '#size'=> 145,
    );
  }
  // $form['access_type'] = array(
  //   '#title' => t('Access'),
  //   '#type' => 'select',
  //   '#id' => 'new_access_type',
  //   '#options' => array('none' => 'none', 'read' => 'read', 'write' => 'write', 'both' => 'both'),
  //   '#required' => TRUE,
  //   '#default_value' => (isset($app_details) ? $app_details['accessType'] : NULL),
  // );
  $form['callback_url'] = array(
    '#title' => t('Callback URL'),
    '#type' => 'textfield',
    '#id' => 'new_callback_url',
    '#default_value' => (isset($app_details) ? $app_details['callbackUrl'] : ''),
    '#required' => TRUE,
    '#size'=> 145,
  );

  // Invoke hook_devconnect_app_attributes to see if a custom module has
  // defined custom attributes to appear in this form.
  $custom_attributes = module_invoke_all('devconnect_app_attributes');
  foreach ($custom_attributes as $machine_name => $attribute) {
    $name = $attribute['name'];
    $default_value = (array_key_exists('default', $attribute) ? $attribute['default'] : NULL);
    $description = (array_key_exists('description', $attribute) ? $attribute['description'] : NULL);
    $required = (array_key_exists('required', $attribute) ? (bool) $attribute['required'] : FALSE);
    $max_length = (array_key_exists('maxlength', $attribute) ? $attribute['maxlength'] : NULL);
    $pattern = (array_key_exists('pattern', $attribute) ? $attribute['pattern'] : NULL);
    $tooltip = (array_key_exists('tooltip', $attribute) ? $attribute['tooltip']: NULL);
    $type = (array_key_exists('type', $attribute) ? $attribute['type'] : 'textfield');

    $form_field_name = 'attribute_' . $machine_name;

    if ($type == 'value') {
      $form[$form_field_name] = array('#type' => 'value', '#value' => $default_value);
    }
    else {
      if (isset($app_details) && isset($app_details['parsed_attributes'][$machine_name])) {
        $default_value = $app_details['parsed_attributes'][$machine_name];
      }

      $form[$form_field_name] = array(
        '#title' => t($name),
        '#type' => $type,
        '#default_value' => $default_value,
        '#required' => $required
      );
      if ($description) {
        $form[$form_field_name]['#description'] = t($description);
      }
      if ($max_length) {
        $form[$form_field_name]['#maxlength'] = $max_length;
      }
      if ($pattern) {
        $form[$form_field_name]['#attributes']['pattern'] = $pattern;
        $form[$form_field_name]['#element_validate'][] = 'devconnect_developer_apps_pattern_validate';
      }
      if ($tooltip) {
        $form[$form_field_name]['#attributes']['title'] = $tooltip;
      }
    }
  }

  try {
    $options = $dc->GetAPIProductsOptions();
  }
  catch (Exception $e) {
    drupal_set_message($e->getMessage(), 'error');
    $options = array(); // TODO: come up with a more elegant way of handling this.
  }

  $api_product_default = array();
  if (isset($app_details) && !empty($app_details['credentials'])) {
    // IMPORTANT: current credential is the last one!
    $credential = end($app_details['credentials']);
    foreach ($credential['apiProducts'] as $api_product) {
      $api_product_default[] = 'prod-' . $api_product['apiproduct'];
    }
  }
  if (empty($api_product_default)) {
    $api_product_default = 'Select API Products'; // TODO: should this be an array?
  }

  $form['api_product'] = array(
    '#title' => t('Product'),
    '#type' => 'select',
    '#id' => 'api_product',
    '#options' => $options,
    '#default_value' => $api_product_default,
    '#multiple' => TRUE,
    '#required' => FALSE, // Per Morgan, this will not always be required.
  );

  // Add jQuery Select List Plugin
  if ($path = libraries_get_path('jquery.selectlist')) {
    drupal_add_js($path . '/scripts/jquery.selectlist.pack.js');
    drupal_add_js(drupal_get_path('module', 'devconnect_developer_apps') . '/devconnect_developer_apps.js');
    drupal_add_css($path . '/css/selectlist.css');
  }

//  if (count($options) == 1) {
//    $api_product = array_keys($options);
//    $form['api_product']['#default_value'] = array($api_product[0] => 1);
//    $form['api_product']['#access'] = FALSE;
//  }

  $form['uid'] = array(
    '#type' => 'value',
    '#id' => 'uid',
    '#value' => $account->uid,
  );

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => $button_caption,
    '#weight' => 10,
    '#submit' => array('devconnect_developer_apps_edit_form_submit')
  );

  $form['#validate'] = array('devconnect_developer_apps_edit_form_validate');

  // Set HTML5 required attribute on all required elements
  /*
  foreach ($form as $key => $value) {
    if (substr($key, 0, 1) != '#' && isset($value['#required']) && $value('#required')) {
      $form[$key]['#attributes']['required'] = 'required';
    }
  }
  */

  return $form;
}

function devconnect_developer_apps_pattern_validate($element, &$form_state, $form) {
  $pattern = '!' . preg_replace('!', '\!', $element['#attributes']['pattern']) . '!';
  if (!preg_match($pattern, $element['#value'])) {
    form_error($element, t('The @title element does not conform to the indicated pattern.', array('@title' => $element['#title'])));
  }
}

function devconnect_developer_apps_edit_form_validate($form, &$form_state) {

  if ($form['machine_name']['#type'] == 'item') {
    // No need to validate existing machine names.
    return;
  }

  if (user_is_logged_in() && $form_state['values']['uid'] == $GLOBALS['user']->uid) {
    $user = $GLOBALS['user'];
  }
  else {
    $user = user_load($form_state['values']['uid']);
  }

  $machine_name = strtolower($form_state['values']['machine_name']);

  $dc = new DevConnectApigeeDeveloperApp($user);
  // Assume app exists until proven otherwise
  $app_exists = TRUE;
  try {
    $results = $dc->GetInfo($machine_name);
  }
  catch (Exception $e) {
    // Some sort of failure occurred, possibly indicating that app could not be retrieved.
    $app_exists = FALSE;
    watchdog('devconnect_developer_apps', $e->getMessage(), array(), WATCHDOG_NOTICE);
  }
  if ($app_exists) {
    if ($results['code_class'] == 4) {
      // A 404 or similar indicates that there is no such app.
      $app_exists = FALSE;
      watchdog('devconnect_developer_apps', "App $machine_name does not yet exist.", array(), WATCHDOG_NOTICE);
    }
    else {
      // Throw form back to user.
      form_error($form['machine_name'], 'The App Name “' . check_plain($machine_name) . '” is already in use. Please select a different name.');
      watchdog('devconnect_developer_apps', "App $machine_name already exists.", array(), WATCHDOG_NOTICE);
    }
  }
}

/**
 * Submit handler for the above form.
 *
 * @param $form
 * @param $form_state
 * @return bool
 */
function devconnect_developer_apps_edit_form_submit($form, &$form_state) {
  $values = $form_state['values'];

  if (user_is_logged_in() && $values['uid'] == $GLOBALS['user']->uid) {
    $values['user'] = $GLOBALS['user'];
  }
  else {
    $values['user'] = user_load($values['uid']);
  }

  $dca = new DevConnectApigeeDeveloperApp($values['user']);
  if ($dca instanceof DevConnectApigeeDeveloperApp) {
    try {
      if (arg(4) == 'edit') {
        $results = $dca->Update(arg(3), $values);
      }
      else {
        $results = $dca->Create($values);
      }
    } catch (Exception $e) {
      $message = $e->getMessage();
      watchdog('devconnect_developer_apps', $message, array(), WATCHDOG_ERROR);
      drupal_set_message('The following error occurred while saving your app: <h4>' . $message . '</h4>', 'error');
      return;
    }
  }
  else {
    watchdog('devconnect_developer_apps', print_r($dca, TRUE), array(), WATCHDOG_ERROR);
    drupal_set_message(t('Error Creating App!'), 'error');
    return;
  }

  if (is_array($results['data']) && $results['code_class'] == 2) {
    watchdog('devconnect_developer_apps', print_r($results, TRUE), array(), WATCHDOG_DEBUG);
    drupal_set_message(t('App Created!'), 'status');
    //$form_state['storage']['response'] = $results['data'];
  }
  else {
    // The following should never occur. Name clashes should have been handled in form validation above.
    // If we encounter a name clash here, log it as CRITICAL -- these items MUST be addressed.
    if ($results['code'] == 409) {
      drupal_set_message('The App Name “' . check_plain($values['machine_name']) . '” is already being used.', 'error');
      watchdog('devconnect_developer_apps', 'Duplicate app name "' . $values['machine_name'] . '" for user "' . $values['user']->name . '"!', WATCHDOG_CRITICAL);
      //drupal_goto('user/' . $values['user']->uid . '/apps/add');
      return;
    }
    else {
      drupal_set_message('There was an error trying to create the application. For more information please review the "Recent log messages".', 'error', FALSE);
    }
  }

  $middle_arg = (module_exists('me') && user_is_logged_in() && $values['uid'] == $GLOBALS['user']->uid ? 'me' : $values['uid']);

  $form_state['redirect'] = 'user/' . $middle_arg . '/apps';

  foreach (module_implements('devconnect_app_save') as $module) {
    $function = $module . '_devconnect_app_save';
    $function($results, $form_state);
  }
}

/**
 * Flattens an app's credentials into an object with four evenly-sized arrays.
 *
 * @param array $credentials
 * @return object
 */
function _devconnect_developer_apps_parse_credential_list($credentials) {
  $fields = (object)array('apiproducts' => array(), 'statuses' => array(), 'consumer_keys' => array(), 'secret_keys' => array());
  foreach ($credentials as $credential) {
    foreach ($credential['apiProducts'] as $product) {
      $fields->apiproducts[] = $product['apiproduct'];
      $fields->statuses[] = $credential['status'];
      $fields->consumer_keys[] = $credential['consumerKey'];
      $fields->secret_keys[] = $credential['consumerSecret'];
    }
  }
  return $fields;
}

/**
 * Form constructor for deleting apps. This is called from a menu callback via drupal_get_form.
 *
 * Incoming URL takes the following form:
 * - user/%user/apps/%/delete
 *
 * @return array
 */
function devconnect_developer_app_delete_form() {

  drupal_set_title(t('Are you sure?'));

  $form = array(
    '#type' => 'form',
    '#attributes' => array(
      'id' => 'devconnect_developer_application_delete',
    ),
  );
  $form['are_you_sure'] = array(
    '#markup' => 'Deleting the ‘' . arg(3) . '’ app will also delete all of its data. This action cannot be undone.<br><br>',
  );

  $form['application'] = array('#type' => 'value', '#value' => arg(3));
  $form['uid'] = array('#type' => 'value', '#value' => arg(1));

  $form['actions'] = array('#type' => 'actions');
  $form['actions']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Delete App'),
    '#weight' => 10,
    '#submit' => array('devconnect_developer_app_delete_form_submit'),
  );

  $user_arg = arg(1);
  if (user_is_logged_in() && $GLOBALS['user']->uid == $user_arg && module_exists('me')) {
    $user_arg = 'me';
  }

  $form['actions']['cancel'] = array(
    '#markup' => l(t('Cancel'), 'user/' . $user_arg . '/apps', array('attributes' => array('class' => array('cancel-link btn')))),
    '#weight' => 11,
  );

  return $form;
}

/**
 * Form submit handler for the above form.
 *
 * @param $form
 * @param $form_state
 */
function devconnect_developer_app_delete_form_submit(&$form, &$form_state) {
  $values = $form_state['values'];
  $user = user_load($values['uid']);
  $result = NULL;
  try {
    $dc = new DevConnectApigeeDeveloperApp($user);
    $result = $dc->Delete($values['application']);
    watchdog('devconnect_developer_apps', print_r($result, TRUE), array(), WATCHDOG_DEBUG);
    if ($result['code_class'] == 2) {
      drupal_set_message(t('App Deleted!'), 'status');
    }
  } catch (Exception $e) {
    watchdog('devconnect_developer_apps', $e->getMessage(), array(), WATCHDOG_ERROR);
    drupal_set_message(t('App could not be deleted.'), 'error');
  }
  $form_state['redirect'] = 'user/' . $values['uid'] . '/apps';
  if (isset($result)) {
    foreach (module_implements('devconnect_app_delete') as $module) {
      $function = $module . '_devconnect_app_delete';
      $function($result, $form_state);
    }
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * @param array $data
 * @param $router_item
 * @param $root_path
 */
function devconnect_developer_apps_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if (arg(0) == 'user') {
    unset($data['tabs']);
  }
}

/**
 * Page callback to display detailed info for a user's app.
 *
 * @param $user
 * @param $app_name
 * @return string
 */
function devconnect_developer_apps_detail($user, $app_name) {


  $dc = new DevConnectApigeeDeveloperApp($user);
  try {
    $results = $dc->GetInfo($app_name);
  } catch (Exception $e) {
    return '<h4>' . $e->getMessage() . '</h4>';
  }

  $data = $results['data'];

  // Set Title
  drupal_set_title($data['name']);

  $description = NULL;
  if (isset($data['description']) && !empty($data['description'])) {
    $description = $data['description'];
  }
  elseif (isset($data['parsed_attributes']['description'])) {
    $description = $data['parsed_attributes']['description'];
  }
  if (!empty($description)) {
    devconnect_developer_apps_set_description($description);
  }

  // Build Breadcrumbs
  $owner_name = ($user->uid == $GLOBALS['user']->uid ? 'My' : $user->name . "'s");
  $breadcrumb = array();
  $breadcrumb[] = l('Home', '<front>');
  $breadcrumb[] = l("$owner_name Apps", 'user/' . $user->uid . '/apps');
  // Set Breadcrumbs
  drupal_set_breadcrumb($breadcrumb);

  $info = array(
    'account' => $user,
    'access_type' => ($data['accessType'] == 'both' ? 'read/write' : $data['accessType']),
    'callback_url' => $data['callbackUrl'],
    'name' => $data['name'],
    'status' => $data['status'],
    'attributes' => array(),
    'credentials' => array()
  );

  foreach ($data['credentials'] as $credential) {
    $cred = array('apiproducts' => array());
    foreach ($credential['apiProducts'] as $api_product) {
      $api_product_info = $dc->GetAPIProductDetail($api_product['apiproduct'], FALSE);
      if (isset($api_product_info['displayName'])) {
        $display_name = $api_product_info['displayName'];
        $description = '';
        if (isset($api_product_info['description']) && strlen($api_product_info['description']) > 0) {
          $description = $api_product_info['description'];
        }
        elseif (!empty($api_product_info['parsed_attributes']['description'])) {
          $description = $api_product_info['parsed_attributes']['description'];
        }
        $cred['apiproducts'][] = array('display_name' => $display_name, 'description' => $description, 'status' => $api_product['status']);
      }
    }
    $cred['consumer_key'] = $credential['consumerKey'];
    $cred['consumer_secret'] = $credential['consumerSecret'];
    $cred['status'] = $credential['status'];
    $info['credentials'][] = $cred;
  }

  $info['app_attributes'] = _devconnect_developer_apps_get_attributes($data['attributes']);
  if (variable_get('devconnect_show_analytics', FALSE)) {
    module_load_include('inc', 'devconnect_developer_apps', 'analytics');
    $info['analytics_chart'] = devconnect_developer_apps_analytics_performance($app_name);
  }

  return theme('devconnect_developer_app', $info);
}

/**
 * Helper function to get displayable attributes.
 *
 * @param $app_attributes
 * @return array
 */
function _devconnect_developer_apps_get_attributes($app_attributes) {
  // Invoke custom hook
  $shown_attributes = module_invoke_all('devconnect_attributes_display_list');
  $items = array();
  foreach ($shown_attributes as $attr_name => $attr_display) {
    foreach ($app_attributes as $result_attr) {
      if ($result_attr['name'] == $attr_name) {
        $items[$attr_display] = $result_attr['value'];
        break;
      }
    }
  }
  return $items;
}

/**
 * Preprocessor for theme('page').
 *
 * @param $variables
 * @return void
 */
function devconnect_developer_apps_preprocess_page(&$variables){
  $description = devconnect_developer_apps_set_description();
  if (isset($description)) {
    $variables['subtitle'] = $description;
  }
}

/**
 * Static getter/setter for app description
 *
 * @param string|null $description
 * @return string|null
 */
function devconnect_developer_apps_set_description($description = NULL) {
  static $desc;
  if (isset($description)) {
    $desc = $description;
  }
  return $desc;
}
